### ISSUE TITLE
Enable the FatFS in Data Flash handler

### ISSUE THREAD

**Issue by svnagendra2003** [Wiznet/FTP_LPC11E36_LPCXpresso#2]
How to enable FatFS in Data Flash Handler?
If we are able to save the data for a while, it is OK at present. 
I referred to ff.c and could not understand where i can enable logging. 
Please let me know how i can enable the FatFS for dataflash.

Also, please give us the contact details of Wiznet R&D team of US or HK.

**Comment by bingdo** [comment]
Already FatFS is included with source code.
Just you can use that by calling public file system functions.
If you don't know a file system, maybe your egineer know that.
Reter to http://elm-chan.org/fsw/ff/00index_e.html
ex.) f_open(), f_write(), f_close() ...

Refer to http://www.wiznet.co.kr/sub_modules/en/aboutus/contactus.asp

Thanks.
